const LLM_PROVIDER = process.env.LLM_PROVIDER || 'openai'
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || ''
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-4'
const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY || ''

export async function callLLM(
  systemPrompt: string,
  userPrompt: string,
  temperature = 0.1
): Promise<string> {
  if (LLM_PROVIDER === 'openai' && OPENAI_API_KEY && OPENAI_API_KEY !== 'sk-your-openai-api-key') {
    return callOpenAI(systemPrompt, userPrompt, temperature)
  }

  if (LLM_PROVIDER === 'google' && GOOGLE_API_KEY) {
    return callGemini(systemPrompt, userPrompt, temperature)
  }

  return callMockLLM(systemPrompt, userPrompt)
}

async function callOpenAI(system: string, user: string, temp: number): Promise<string> {
  const res = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      messages: [
        { role: 'system', content: system },
        { role: 'user', content: user },
      ],
      temperature: temp,
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`OpenAI API error: ${err}`)
  }

  const data = await res.json()
  return data.choices[0].message.content || ''
}

async function callGemini(system: string, user: string, temp: number): Promise<string> {
  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GOOGLE_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `${system}\n\n${user}` }] }],
        generationConfig: { temperature: temp },
      }),
    }
  )

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`Gemini API error: ${err}`)
  }

  const data = await res.json()
  return data.candidates?.[0]?.content?.parts?.[0]?.text || ''
}

async function callMockLLM(system: string, user: string): Promise<string> {
  await new Promise(r => setTimeout(r, 500))

  const lower = user.toLowerCase()

  if (lower.includes('approve leave') || lower.includes('leave balance')) {
    return JSON.stringify({
      reasoning: 'The user wants to process a leave request. I need to check employee details, leave balance, and company policy before approving or rejecting.',
      requiresConfirmation: false,
      steps: ['retrieve_employee', 'check_leave_balance', 'check_policy', 'approve_leave'],
      selectedTool: 'approve_leave',
      action: 'approve_leave',
      explanation: 'Leave approved based on sufficient balance and policy compliance.',
    })
  }

  if (lower.includes('delete') || lower.includes('remove')) {
    return JSON.stringify({
      reasoning: 'This is a delete operation which requires human confirmation due to its destructive nature.',
      requiresConfirmation: true,
      steps: ['confirm_deletion', 'execute_delete'],
      selectedTool: lower.includes('employee') ? 'delete_employee' : 'delete_product',
      action: 'confirm_required',
      explanation: 'Deletion actions require manual confirmation to prevent accidental data loss.',
    })
  }

  if (lower.includes('inventory') || lower.includes('stock')) {
    return JSON.stringify({
      reasoning: 'The user wants inventory information. I will search the inventory database and return current stock levels.',
      requiresConfirmation: false,
      steps: ['search_inventory'],
      selectedTool: 'search_knowledge',
      action: 'search_knowledge',
      explanation: 'Retrieving inventory data from internal database.',
    })
  }

  if (lower.includes('report') || lower.includes('summary')) {
    return JSON.stringify({
      reasoning: 'The user wants a report. I will gather data from multiple sources and compile a summary.',
      requiresConfirmation: false,
      steps: ['fetch_employees', 'fetch_products', 'fetch_inventory', 'generate_report'],
      selectedTool: 'generate_report',
      action: 'generate_report',
      explanation: 'Report generated by aggregating data from all internal sources.',
    })
  }

  if (lower.includes('audit') || lower.includes('log')) {
    return JSON.stringify({
      reasoning: 'The user wants to view audit logs. I will retrieve recent audit log entries.',
      requiresConfirmation: false,
      steps: ['fetch_audit_logs'],
      selectedTool: 'view_audit_logs',
      action: 'view_audit_logs',
      explanation: 'Retrieving audit logs from the database.',
    })
  }

  if (lower.includes('policy') || lower.includes('rule') || lower.includes('company policy')) {
    return JSON.stringify({
      reasoning: 'The user wants information about company policies. I will search the knowledge base.',
      requiresConfirmation: false,
      steps: ['search_policies'],
      selectedTool: 'search_knowledge',
      action: 'search_knowledge',
      explanation: 'Searching company policy documents from internal knowledge base.',
    })
  }

  return JSON.stringify({
    reasoning: 'I need to understand what the user wants and find the relevant information from internal knowledge sources.',
    requiresConfirmation: false,
    steps: ['search_knowledge'],
    selectedTool: 'search_knowledge',
    action: 'search_knowledge',
    explanation: 'Searching internal knowledge sources to answer the query.',
  })
}
